pipeline{


    agent{
    }


    stages{
        stage('Build'){
            steps{

            }

        }
        stage('Test'){
            steps{

            }
        }
        stage('Deliver'){
            steps{

            }
        }
    }
}